# Support the author by using the funding links below
# Developed and maintained by †La'lan†
# GitHub Sponsors: https://github.com/sponsors/THRVN
# Buy Me a Coffee: https://buymeacoffee.com/THRVN

github: THRVN
buy_me_a_coffee: THRVN

# Your support means a lot to me to continue the development of open source project like this.
# Sponsoring this project means a lot to me. Your support helps me to continue building great open-source projects just like this.